# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "marketplace-merchant"
client_id = "9830f64fe92253bf0e35ad60e901d3bc"
application_url = "https://whale-ample-tightly.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_draft_orders,unauthenticated_read_product_listings,read_product_listings"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://whale-ample-tightly.ngrok-free.app/auth/callback",
  "https://whale-ample-tightly.ngrok-free.app/auth/shopify/callback",
  "https://whale-ample-tightly.ngrok-free.app/api/auth/callback",
  "https://whale-ample-tightly.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nice-t-shirt-store.myshopify.com"
