version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app # mount code -> container, necessary to avoid image rebuilding on every change
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_DEV_URL=${DATABASE_DEV_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - DATABASE_PROD_URL=${DATABASE_PROD_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - web-db

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
