version: '3.8' # Docker compose file version

services:
  web:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 # run command on container start
    volumes:
      - ./:/usr/src/app # mount code -> container, necessary to avoid image rebuilding on every change
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
    depends_on:
      - web-db

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
