POST http://localhost:8004/users/user_2RYsQv4W7NG9YYHaOId6Tq599SV/plists HTTP/1.1
content-type: application/json

{
    "id": "wishlist"
}

###
POST http://localhost:8004/users/user_2RYsQv4W7NG9YYHaOId6Tq599SV/plists HTTP/1.1
content-type: application/json

{
    "id": "wlas",
    "product_urls": [
        "https://softgoat.com/p/mens-fine-knit-t-shirt-light-grey",
        "https://softgoat.com/p/mens-fine-knit-t-shirt-white"
    ]
}

###

DELETE http://localhost:8004/users/user_2RYsQv4W7NG9YYHaOId6Tq599SV/plists HTTP/1.1
content-type: application/json

{
    "id": "baggie"
}

###
POST http://localhost:8004/users/user_2RYsQv4W7NG9YYHaOId6Tq599SV/plists/wishlist/products HTTP/1.1
content-type: application/json

{
    "id": "wlas",
    "productUrl": "https://softgoat.com/p/mens-collar-navy"
}